(define (problem robot-battery-prob)
  (:domain robot-battery)
  (:objects
    leia - robot
    A B C D charging - location
  )
  (:init
    (at leia A)
    (charging_point_at charging)
    (= (battery leia) 30)
    (connected A B)
    (connected B A)
    (connected B C)
    (connected C B)
    (connected C D)
    (connected D C)
    (connected A charging)
    (connected charging A)
    (= (distance A B) 10)
    (= (distance B A) 10)
    (= (distance B C) 10)
    (= (distance C B) 10)
    (= (distance C D) 10)
    (= (distance D C) 10)
    (= (distance A charging) 5)
    (= (distance charging A) 5)
  )
  (:goal (at leia D))
)